apiVersion: v1
kind: Service
metadata:
        name: cloud7-helloworldapp-svc
spec:
        selector:
                app: microservices
                tier: frontend
        ports:
              - targetPort: 8080
                port: 8080
                nodePort: 30008
        type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: cloud7-helloworldapp-dpt
        labels:
                app: microservices
                tier: frontend


spec:
        replicas: 1
        selector:
                app: microservices
                tier: frontend

        template:
                metadata:
                        labels:
                                app: microservices
                                tier: frontend
                spec:
                         containers:
                              - name: microservices-app
                                image: registry.gitlab.com/bhatanimesh02/springboot-helloworld
                                ports:
                                      - containerPort: 8080
